previews:
  generation: off
services:
- type: web
  runtime: docker
  name: backend-api
  plan: free
  numInstances: 1
  dockerfilePath: apps/backend/Dockerfile
  buildFilter:
    paths:
      - apps/backend/**
      - packages/python/**
  envVars:
    - fromGroup: Backend-Environment
    - key: SERVICE_TYPE
      value: api
    - key: BACKEND_API_URL
      value: https://backend-api.onrender.com
      previewValue: https://backend-api-staging.onrender.com
    - key: JOB_DOMAIN
      value: default

- type: worker
  runtime: docker
  name: backend-worker
  plan: free
  numInstances: 1
  dockerfilePath: apps/backend/Dockerfile
  buildFilter:
    paths:
      - apps/backend/**
      - packages/python/**
  envVars:
    - fromGroup: Backend-Environment
    - key: SERVICE_TYPE
      value: worker
    - key: BACKEND_API_URL
      value: https://backend-api.onrender.com
      previewValue: https://backend-api-staging.onrender.com
    - key: JOB_DOMAIN
      value: default

- type: cron
  runtime: docker
  name: backend-message
  schedule: "0 */6 * * *"
  plan: free
  dockerfilePath: apps/backend/Dockerfile
  buildFilter:
    paths:
      - apps/backend/**
      - packages/python/**
  dockerCommand: python -m src.jobs.dispatch_backend_message
  envVars:
    - fromGroup: Backend-Environment
    - key: BACKEND_API_URL
      value: https://backend-api.onrender.com
      previewValue: https://backend-api-staging.onrender.com
    - key: JOB_DOMAIN
      value: default
