previews:
  generation: off
services:
- type: web
  runtime: docker
  name: fiery-ai-api
  plan: free
  numInstances: 1
  dockerfilePath: apps/ai/Dockerfile
  buildFilter:
    paths:
      - apps/ai/**
      - packages/python/**
  envVars:
    - fromGroup: Fiery-Environment
    - key: SERVICE_TYPE
      value: api
    - key: BACKEND_API_URL
      value: https://fiery-backend-api.onrender.com
      previewValue: https://fiery-backend-api-staging.onrender.com
    - key: AI_API_URL
      value: https://fiery-ai-api.onrender.com
      previewValue: https://fiery-ai-api-staging.onrender.com
    - key: TRAINER_API_URL
      value: https://fiery-trainer-api.modal.run
      previewValue: https://fiery-trainer-api-staging.modal.run
    - key: JOB_DOMAIN
      value: training

- type: worker
  runtime: docker
  name: fiery-ai-worker
  plan: free
  numInstances: 1
  dockerfilePath: apps/ai/Dockerfile
  buildFilter:
    paths:
      - apps/ai/**
      - packages/python/**
  envVars:
    - fromGroup: Fiery-Environment
    - key: SERVICE_TYPE
      value: worker
    - key: BACKEND_API_URL
      value: https://fiery-backend-api.onrender.com
      previewValue: https://fiery-backend-api-staging.onrender.com
    - key: AI_API_URL
      value: https://fiery-ai-api.onrender.com
      previewValue: https://fiery-ai-api-staging.onrender.com
    - key: TRAINER_API_URL
      value: https://fiery-trainer-api.modal.run
      previewValue: https://fiery-trainer-api-staging.modal.run
    - key: JOB_DOMAIN
      value: training
