export const TEST_IDS = {
  homeScreen: "home-screen",
  homeMessagesHeading: "home-messages-heading",
  homeMessages: "home-messages",
  homeMessageButton: "home-message-button",
  openAdminLink: "open-admin-link",
  createProfileLink: "create-profile-link",
  signupDialog: "signup-dialog",
  signupCloseButton: "signup-close-button",
  signInButton: "sign-in-button",
  loginDialog: "login-dialog",
  loginCloseButton: "login-close-button",
  myProfileButton: "my-profile-button",
  myProfileDialog: "my-profile-dialog",
  myProfileCloseButton: "my-profile-close-button",
  myProfileNameField: "my-profile-name-field",
  myProfileEmailField: "my-profile-email-field",
  adminScreen: "admin-screen",
  backTofrontendLink: "back-to-frontend-link",
  adminMessagesHeading: "admin-messages-heading",
  adminMessages: "admin-messages",
  adminToolbar: "admin-toolbar",
  adminMessageButton: "admin-message-button",
} as const;
