#!/usr/bin/env python3
"""
Author: Sean Froning
Created Date: 9.8.2026
Print thalia_label to frame_id mapping
"""

import csv
import sys

_THALIA_LABELS = (
    "Tupungato",
    "Tupungatito",
    "Nevado de los Piuquenes",
    "San José",
    "Maipo",
    "Caldera del Atuel",
    "Palomo",
    "Northern Mendoza Volcanic Field",
    "Tinguiririca",
    "Risco Plateado",
    "Sordo Lucas",
    "Infiernillo",
    "Planchón-Peteroa",
    "Descabezado Grande",
    "Cerro Azul",
    "azul",
    "Llancanelo Volcanic Field",
    "Puelche Volcanic Field",
    "San Pedro-Pellado",
    "Nevado de Longaví",
    "Lomas Blancas",
    "Payún Matrú",
    "Resago",
    "Cochiquito Volcanic Group",
    "Nevados de Chillan",
    "Tromen",
    "Puntiagudo-Cordón Cenizos",
    "Osorno",
    "Tronador",
    "Yate",
    "hornopiren",
    "Huequi",
)

_FRAME_VOLCANOES = {
    "162A_06192_060402": (
        "Gran Canaria",
        "Tenerife",
    ),
    "128D_09016_110500": (
        "Fernandina",
        "Sierra Negra",
        "ecuador",
        "santiago",
        "wolf",
    ),
    "021D_09150_131313": (
        "Karisimbi",
        "Muhavura",
        "Nyamuragira",
        "Nyiragongo",
        "Tshibinda",
        "Visoke",
    ),
    "156A_05796_080500": (
        "Aira",
        "kirishimayama",
        "yonemaru-sumiyoshiike",
    ),
    "012D_07075_080504": ("Colima",),
    "115D_04601_131313": (
        "Blue Lake Crater",
        "Cinnamon Butte",
        "Crater Lake",
        "Davis Lake",
        "Devils Garden",
        "Jefferson",
        "Newberry",
        "Sand Mountain Field",
        "Three Sisters",
    ),
    "022D_04826_121209": (
        "Campi Flegrei",
        "colli_albani",
        "Ischia",
        "vesuvius",
    ),
    "032D_09854_070505": (
        "Batur",
        "Buyan-Bratan",
        "Rinjani",
    ),
    "152D_09114_131313": (
        "Elmenteita Badlands",
        "Homa Mountain",
        "Longonot",
        "Menengai",
        "Ol Doinyo Eburru",
        "Olkaria",
    ),
    "155D_02579_100800": (
        "Geysir",
        "Grensdalur",
        "Grimsnes",
        "Helgrindur",
        "Hengill",
        "Hromundartindur",
        "Krysuvik",
        "Ljosufjoll",
        "Prestahnukur",
        "Reykjanes",
    ),
    "106A_09090_000404": (
        "Cerro Azul",
        "Sierra Negra",
    ),
    "103A_07010_121313": ("Tin Zaouatene Volcanic Field",),
    "175D_12845_111312": (
        "Okataina",
        "Rotorua",
        "Taupo",
        "Maroa",
        "Moutohora Island",
        "Reporoa",
        "white_island",
    ),
    "174A_09133_131313": (
        "Bufumbira",
        "Bunyaruguru",
        "Karisimbi",
        "Katunga",
        "Muhavura",
        "Nyamuragira",
        "Nyiragongo",
        "Tshibinda",
        "Visoke",
    ),
    "076D_09725_121107": (
        "Dieng Volcanic Complex",
        "Lawu",
        "Merapi",
        "Merbabu",
        "Muria",
        "Slamet",
        "Sundoro",
        "Telomoyo",
        "Ungaran",
    ),
    "142A_07606_131313": (
        "Taal",
        "Banahaw",
        "Laguna Caldera",
        "Malindig",
        "Mariveles",
        "Natib",
        "Panay",
        "San Pablo Volcanic Field",
    ),
    "124D_05291_081406": ("Etna",),
    "124D_04854_171313": (
        "Campi Flegrei",
        "Ischia",
        "vesuvius",
    ),
    "083D_12636_131313": (
        "Cerro Azul",
        "Cochiquito Volcanic Group",
        "Descabezado Grande",
        "Llancanelo Volcanic Field",
        "Lomas Blancas",
        "Nevado de Longaví",
        "Nevados de Chillan",
        "Payún Matrú",
        "Puelche Volcanic Field",
        "Resago",
        "San Pedro-Pellado",
        "Tromen",
        "azul",
    ),
    "014A_07688_131313": (
        "Nabro",
        "Gada Ale",
        "Alayta",
        "Ale Bagu",
        "Alu-Dalafilla",
        "Asavyo",
        "Bora Ale",
        "Borawli",
        "Dabbahu",
        "Dabbayra",
        "Dubbi",
        "Erta Ale",
        "Hayli Gubbi",
        "Ma Alalta",
        "Manda Hararo",
        "Manda-Inakir",
        "Mat Ala",
        "Tat Ali",
        "afdera",
        "mallahle",
        "sork_ale",
    ),
    "152D_08915_131313": (
        "Emuruangogolak",
        "Korosi",
        "Menengai",
        "Ol Kokwe",
        "Paka",
    ),
    "109D_05390_141615": (
        "Milos",
        "Santorini",
    ),
    "079D_05011_131313": (
        "Ghegam Ridge",
        "Porak",
        "Tskhouk-Karckar",
        "Unnamed",
    ),
    "146D_12613_231107": (
        "Auckland Field",
        "Kaikohe-Bay of Islands",
        "Taranaki [Egmont]",
        "Whangarei",
    ),
    "164A_13146_131313": (
        "Huequi",
        "Osorno",
        "Puntiagudo-Cordón Cenizos",
        "Tronador",
        "Yate",
        "hornopiren",
    ),
    "079D_07694_131313": (
        "Hayli Gubbi",
        "Kurub",
        "Ma Alalta",
        "Manda Hararo",
        "Mat Ala",
        "Tat Ali",
        "afdera",
        "mallahle",
    ),
    "169D_00001_020800": (
        "Hierro",
        "La Palma",
    ),
    "005A_07021_131313": (
        "Chichinautzin",
        "Cofre de Perote",
        "Iztaccíhuatl",
        "La Malinche",
        "La",
        "Gloria",
        "Las Cumbres",
        "Los Humeros",
        "Papayo",
        "Pico de Orizaba",
        "Popocatépetl",
        "Serdán-Oriental",
        "la_gloria",
    ),
    "155D_02484_191814": (
        "Grensdalur",
        "Grimsnes",
        "Helgrindur",
        "Hengill",
        "Hromundartindur",
        "Krysuvik",
        "Langjokull",
        "Ljosufjoll",
        "Prestahnukur",
        "Reykjanes",
        "Snaefellsjokull",
    ),
    "086A_06208_131313": (
        "Bazman",
        "Taftan",
        "kuh-e_nader",
    ),
    "083D_12440_131313": (
        "Caldera del Atuel",
        "Infiernillo",
        "Maipo",
        "Nevado de los Piuquenes",
        "Northern Mendoza Volcanic Field",
        "Palomo",
        "Planchón-Peteroa",
        "Risco Plateado",
        "San José",
        "Sordo Lucas",
        "Tinguiririca",
        "Tupungatito",
        "Tupungato",
    ),
    "049A_07091_051113": ("Colima",),
    "032D_07536_111313": (
        "Arayat",
        "Banahaw",
        "Laguna Caldera",
        "Mariveles",
        "Natib",
        "Panay",
        "Pinatubo",
        "San Pablo Volcanic Field",
    ),
    "087D_07004_060904": (
        "Haleakala",
        "Hualalai",
        "Hualalai2",
        "Kilauea",
        "Mauna Kea",
        "Mauna Loa",
    ),
    "081A_12881_141414": (
        "Okataina",
        "Rotorua",
        "Taupo",
        "Maroa",
        "Reporoa",
        "Ruapehu",
        "Tongariro",
    ),
    "115D_04999_131313": (
        "Lassen Volcanic Center",
        "Clear Lake",
        "Silver Lake",
    ),
    "144A_SM_REUN_S6": ("Piton de la Fournaise",),
    "151D_SM_REUN_S4": ("Piton de la Fournaise",),
}


writer = csv.writer(sys.stdout)
writer.writerow(("thalia_label", "frame_id"))
for label in _THALIA_LABELS:
    for frame_id, volcanoes in _FRAME_VOLCANOES.items():
        if label in volcanoes:
            writer.writerow((label, frame_id))
